### PR TITLE
Tweak ash texture

### PR DESCRIPTION
**Pull request by oitsjustjose**
Sorry for the not-so-helpful PR, just thought I'd offer to help change a texture. 

I'm no texture artist, but the default ash texture being the same as light-gray dye makes for some decent confusion in some situations.

### CODE REVIEW

**Comment by Nedelosk** [comment]
@mezz What do you think about this change ?

**Comment by mezz** [comment]
Not sure, it has been this way forever. I would like to keep it similar to the original, maybe tweak it less drastically.

**Comment by oitsjustjose** [comment]
Fair enough. I can work on it some.. I’m only worried because the default ash texture is *literally* Light Gray dye’s texture.

**Comment by asiekierka** [comment]
@oitsjustjose Maybe keep the ash's color light gray-ish, but change the shape like you have done?

**Comment by oitsjustjose** [comment]
image


Better?

**Comment by asiekierka** [comment]
I'd keep a dark outline to match vanilla items, but... seems better.

**Comment by Nedelosk** [comment]
@oitsjustjose Any update ?

**Comment by oitsjustjose** [comment]
preview

**Comment by mezz** [comment]
The latest image looks good to me, please update this PR.

**Comment by oitsjustjose** [comment]
Done! :)

**Review by mezz — APPROVED** [review]

**Pull request merged**
