### PR TITLE
Move 1.7.10-3.6 To 1.8-3.6

### PR DESCRIPTION
**Pull request by Nedelosk**

### CODE REVIEW

**Comment by mezz** [comment]
How's it going @Nedelosk ?

**Comment by Nedelosk** [comment]
I make a new 1.8-4 Version.

**Comment by mezz** [comment]
@Nedelosk any update? I think I would like to work on this soon too.

**Comment by Nedelosk** [comment]
I will make a new Version, when 1.9 Forge is out.

**Comment by mezz** [comment]
Ok I think I will work on 1.8.8 then. Do you have a branch I can start from?

**Comment by Nedelosk** [comment]
My branch is to old. I thin it's better when you make a new branch with the code from 1.7. And I make a PR with my changes. When I have finished my Mod than I help you with 1.8.8.

Sorry for my bad english.

**Comment by Nedelosk** [comment]
My Mod is finished. I work now on the 1.8.8 Version of Forestry. Later I open an new PR.

**Pull request closed without merging**
