### PR TITLE
Update greenhouse climate system and improve camouflage system

### PR DESCRIPTION
**Pull request by Nedelosk**

### CODE REVIEW

**Comment by mezz** [comment]
Crash when placing a sprinkler on the ceiling of a complete greenhouse:
https://gist.github.com/mezz/2c586edb9f8b5bb79fcc6de031d11b5a

**Comment by mezz** [comment]
Crash when breaking the sprinkler on the ceiling of a complete greenhouse:
https://gist.github.com/mezz/ede331b2541e23ec971a487800dafe44

Please test more, each time I check this I crash in 1 minute

**Comment by mezz** [comment]
Are you able to see this crash, or is it because I have an old greenhouse? I can try again with a new greenhouse.

**Comment by Nedelosk** [comment]
I hope that i have fixed all bugs.

**Comment by mezz** [comment]
After breaking and replacing a sprinkler quickly in a large greenhouse, I get this crash:
https://gist.github.com/mezz/f133ff669e756fbac968a7b47cbaec09

**Comment by mezz** [comment]
I have done some more testing and this seems good for further testing in alpha.

**Pull request merged**
