### PR TITLE
Add self-pollination of leaves near bees

### PR DESCRIPTION
**Pull request by temp1011**
Closes https://github.com/ForestryMC/ForestryMC/issues/1625.

I've added self pollination of leaves around bee hives in the same way as normal pollination occurs (but without the hive collecting pollen). It is configurable but is on by default. I took the chance of it down but I'm happy to tweak numbers. The chance is separate so this won't slow down normal pollination.

### CODE REVIEW

**Comment by Nedelosk** [comment]
That was not the idea behind #1625. The idea was to breed the sapling with itself at the moment the player breaks the leaf.

**Comment by temp1011** [comment]
I thought this would be better otherwise a player could just bonemeal and break a tree to breed it without any need for bees. However if this is wrong please close

**Comment by mezz** [comment]
I do not think I understand this implementation.
Why is this copied from the existing pollination code, and not just part of it?
The idea of bees pollinating the leaves makes sense to me though.

**Review by mezz — CHANGES_REQUESTED** [review]
I don't think this logic is quite right.
The check for self-pollination is in `TileLeaves#canMateWith` and in `CheckPollinatableTree#canMateWith`.
I think you can alter the logic in those two places so that it looks at `ModuleApiculture.doSelfPollination` and skips the check for `isGeneticEqual`.

**Comment by temp1011** [comment]
Yep that's much nicer, sorry.

**Comment by mezz** [comment]
Cool, looks good to me.

**Review by mezz — APPROVED** [review]

**Pull request merged**
