### PR TITLE
[WIP] Removed stained glass

### PR DESCRIPTION
**Pull request by buttilda**
This refers to issue #809

Things missing for the PR to be complete:

-Decide how much Stained Glass should be produced by the Thermionic Fabricator (at the moment I set the value to a random 4)

-Implement the mapping replacement event. I tried but just couldn't get it to work... anything I did just corrupted the world. I'm hoping someone can give me some insight on how to do it.

### CODE REVIEW

**Comment by mezz** [comment]
Confirmed that mapping from modded to vanilla doesn't work.
We'll probably have to add a ticking tile entity that replaces itself with vanilla glass.
I'm going to sleep on it and then ask around a bit to be sure.

**Comment by buttilda** [comment]
Okay :) Let me know what you decide.
What about the amount of glass made by the thermionic fabricator? Is 4 enough or should I change it?

**Comment by mezz** [comment]
I haven't found a satisfactory way to migrate the old blocks to the new type. I think it's best to take advantage of this 4.0 release to simply break the blocks.

**Comment by mezz** [comment]
Merged here https://github.com/ForestryMC/ForestryMC/commit/e9674795060a678531bf4f7b476594f0b3f2baea

**Pull request closed without merging**
