### PR TITLE
Add config option to add a chance of additional princess spawn.

### PR DESCRIPTION
**Pull request by Nirek-K**
Add config option to add a chance of additional princess spawn for skyblock/limited land maps/servers

### CODE REVIEW

**Comment by CovertJaguar** [comment]
A new style was applied in issue #477. I don't know the details of curly braces though.

**Comment by mezz** [comment]
I've been hitting the auto-format button on all PRs, no worries. I went with "braces on everything" because it was difficult to construct a rule for each variation and I don't have a strong opinion on it. I tried to match the existing style as well as I could.

**Comment by CovertJaguar** [comment]
This is generally a pretty good overview of universally adopted Java conventions (mostly dealing with names): http://www.cwu.edu/~gellenbe/javastyle/index.html

You can't go wrong if you stick to the rules described on that site. 

However it doesn't cover more esoteric conventions like braces and various other spacing and layout choices as those tend to vary from project to project and programmer to programmer.

**Comment by Parker8283** [comment]
Maybe a page on the Wiki or in CONTRIBUTING.md, we could include the code style in plain text? May be useful to some people who can't work with the IntelliJ Formatting Profile. And also so we have an easier reference to the code style.

**Comment by mezz** [comment]
Thanks Nirek, merged: https://github.com/ForestryMC/ForestryMC/commit/2b4dfcdae353bd497acf7c1c62f9b2dfd4319ccd

I think the code style is clear now that it's consistent everywhere, and I'll be reformatting PRs since I need to test them anyway. It's really easy to hit the auto-format button.

**Pull request closed without merging**
