### PR TITLE
Have trade station compare tags when accepting payment

### PR DESCRIPTION
**Pull request by LunaticExperimentalist**
Potential fix to #1847.

### CODE REVIEW

**Comment by LunaticExperimentalist** [comment]
I'm going to comment that the change a made here "just works," but is maybe not optimal. The patch changes how Forestry compares ItemStacks at a low level that I thought logical. This patch will also effect how recipes are applied, and I don't know enough about the internals of Forestry to know whether that will cause more problems than it solves.
Another option here may be to give the trade station it's own code for comparing ItemStacks, and/or implement note 3 of #496.

**Comment by mezz** [comment]
Thanks!
Unfortunately you are probably right in thinking that this could have unintended side effects, I'm not sure it's the right fix.

**Comment by LunaticExperimentalist** [comment]
I made some improvements. There's a boolean flag to indicate that strict tag matching should be used. This should have zero effect on existing references to containsSets.

**Comment by mezz** [comment]
Thank you, this looks much safer. This way we can look into the other machines another time.

**Pull request merged**
