### PR TITLE
Add custom fertilizers support

### PR DESCRIPTION
**Pull request by estebes**
Implemented the ability to add custom fertilizers to farms. Also used this to add ic2 fertilizer support to farms as well as allowing it as fermenter fuel. Not sure if it is the best way of doing it but it probably can be used as a base for a better implementation.

### CODE REVIEW

**Comment by Vexatos** [comment]
If I remember correctly, I requested this long ago and it was rejected for some important reason. Not sure if it should become a thing (can't remember the exact reasoning).

**Comment by Vexatos** [comment]
Found it: Issue https://github.com/ForestryMC/ForestryMC/issues/580.

**Comment by Vexatos** [comment]
The main issue is that forestry fertilizer is supposed to be the only non-renewable thing you have to keep your farms supplied with (even if it's cheap and you get lots of fertilizer for little apatite). A major balance point (makes you still have to worry about _something_ after having set up a farm); most mods' fertilizers aren't built this way.

**Comment by Nirek-K** [comment]
Eh, times change, as linked by that issue this was claimed as a milestone for 1.9 anyway. I already added something similar to 1.7 in a more limited fashion to not break apis and things.

**Comment by Vexatos** [comment]
I still think it's something you should consider. I do appreciate it as a balance point, doesn't make the farms "set it and forget it".

**Comment by SandGrainOne** [comment]
As long as there is a somewhat involving process that would need automation. Forestry is one of the best mods to include processes and cross system resource demands. It is something that should be cultivated.

Maybe also try to include new ways to use Apatite.

**Comment by Forecaster** [comment]
It looks like this is hard coded?
Could you add a white-list system similar to the backpack configs for this?
I'd like to be able to keep it limited to apatite in my pack. I like auto-farming being tied to a finite resource.

And automation is still set-and-forget when it uses infinite resources as input.

**Comment by Vexatos** [comment]
> And automation is still set-and-forget when it uses infinite resources like plants as input.

I fully agree with @Forecaster on this one. Fully automating a farm doesn't take long and is only mildly involved anyway.

**Comment by CovertJaguar** [comment]
Yeah, user configurable (whitelist) is probably ok, but I'd really think twice about making it addon/mod configurable (IMC). There are a lot of mods out there that think it is funny to completely throw other mods balance out the window. And even more that wouldn't even give any thought to it beyond "oh! let's make our awesome new rock fertilizer compatible!", and not even look at the design behind it.

**Comment by Vexatos** [comment]
Isn't IC2 fertilizer partially made of scrap? It would actually be cobblestone fertilizer :wink:

**Comment by PrincessOfEvil** [comment]
Isn't Forestry fertilizer made of sand? I'm not sure what balance you're
talking about.

**Comment by Vexatos** [comment]
@laz2727 Apatite.

**Comment by Drullkus** [comment]
I'd like to have this. Still not merged, apparently.

**Comment by Vexatos** [comment]
After the clarification in #580, I do not think this should be merged at all.

**Comment by Nedelosk** [comment]
I close this, because we will not pull this.

**Pull request closed without merging**
