### PR TITLE
Update greenhouse climate system and improve camouflage system

### PR DESCRIPTION
**Pull request by Nedelosk**

### CODE REVIEW

**Comment by mezz** [comment]
With a VERY large greenhouse, I get this error:
https://gist.github.com/mezz/c5fa37f020fc02b94a5244bfb9f0a5d6

I used the builder wand from this mod to place many blocks easily: http://minecraft.curseforge.com/projects/not-enough-wands

**Comment by Nedelosk** [comment]
I thinking this PR is ready for a new test @mezz .

**Comment by mezz** [comment]
I get a crash when trying to load my world with a greenhouse:
https://gist.github.com/mezz/b418a9cc0b3d821a7c64a964e1c326f2

**Comment by Nedelosk** [comment]
I think it is fixed.

**Comment by mezz** [comment]
I think it looks good so far from testing in-game. Can you make a new PR that targets mc-1.10? It is hard to look at the code changes when it is merged like this.

**Pull request closed without merging**
