### PR TITLE
Version 1.8.8

### PR DESCRIPTION
**Pull request by Nedelosk**

### CODE REVIEW

**Comment by Nedelosk** [comment]
The 1.8.8 Version of the ForestryMC dev branch with all commits from the dev branch.

**Comment by mezz** [comment]
Thanks for your work @Nedelosk! I can take over from here.

**Comment by Nedelosk** [comment]
:smile:

**Comment by Nedelosk** [comment]
My new To-Do List:
- [ ] Fix Multiblocks
- [ ] Fix Butterfly Model

**Comment by mezz** [comment]
Nedelosk I think that it is better to start again from dev branch.
It looks like there are many small things broken right now.
1.7.10 development is stopped, so it is a good time to work from dev.
You should keep this branch as a reference to look at for the models and many other things.

There are more modders who want to work on this from dev, if you don't want to do all that again.

**Comment by Nedelosk** [comment]
No problem. I have enough time to do this at the moment. I make it for 1.8.9 ok ?

**Comment by mezz** [comment]
Yes that sounds good. I may make a 1.8.9 official branch soon so people can work together and make PRs.

**Comment by Nedelosk** [comment]
Good. I close the RP. And start to develop the new Version. When I have questions I ask you over the IRC.

**Pull request closed without merging**
