### PR TITLE
ExUtil support:

### PR DESCRIPTION
**Pull request by Nirek-K**
New Managed Farm: Ender (Tube:Ender Eye)
Places Endstone, plants Enderlily seeds

### CODE REVIEW

**Comment by Vexatos** [comment]
I wouldn't want the ability to automate Ender Lilies.
If this gets merged, there should be a config option that is turned off by default.

**Comment by Adaptivity** [comment]
@Vexatos :+1: I think there nothing bad in adding it BUT there are should be a config option.

**Comment by mezz** [comment]
Thanks, merged! https://github.com/ForestryMC/ForestryMC/commit/870906188cd8672eab145938e5a7ef2652c21a7c

**Comment by CovertJaguar** [comment]
Related to issue #223

**Pull request closed without merging**
