### PR TITLE
Include forestry prefix when logging

### PR DESCRIPTION
**Pull request by temp1011**
See https://gist.github.com/temp1011/291c85c53b80a9f66a418cfc7315e8ee. This makes it clearer to see which mod is doing what in big packs. Maybe there is a better way to do this through forge or logger configuration.

### CODE REVIEW

**Comment by mezz** [comment]
No no no. Do this with logger configuration.
If you have logs like this, you're probably using the vanilla launcher which forces some bad log settings.
Try using MultiMC, it will use Forge's log settings and you will see all the proper mod prefixes.

**Comment by temp1011** [comment]
Ok. I was just running from IDEA which didn't do this for some reason.

**Comment by mezz** [comment]
Make sure you are using the latest Forge and IDEA, it should be working properly.

**Comment by temp1011** [comment]
I'm pretty sure I am up to date. It's probably just one of a few weird errors I seem to get.
EDIT: Maybe something to do with this:
```
2018-05-27 20:58:02,635 main WARN Plugin [terminalconsole] is already mapped to class net.minecraftforge.server.console.log4j.TerminalConsoleAppender, ignoring class net.minecraftforge.server.console.TerminalConsoleAppender
```

**Comment by mezz** [comment]
Hm that's pretty strange

**Pull request closed without merging**
