### PR TITLE
Fixing the Infuser to accept valid inputs

### LINKED ISSUE #602: Infuser Does Not Accept Valid Inputs
Tested with both forestry_1.7.10-3.5.3.11.jar and a local gradle build of the latest source at the time of writing (784a47b).

Steps to reproduce:

- Start a new creative world.
- Add an Infuser, Pollen Cluster, Crystalline Pollen Cluster, and Short Mead to the player's inventory.
- Open the Infuser GUI.
- Try to put Pollen Cluster into an item slot tagged as "(No Effect)"

Expected: the inventory accepts the Pollen Cluster item, and the description changes from "(No Effect)" to "Strong Curative".
Actual: the inventory rejects the Pollen Cluster item.

- Try to put Crystalline Pollen Cluster into an item slot tagged as "(No Effect)"

Expected: the inventory accepts the Crystalline Pollen Cluster item, and the description changes from "(No Effect)" to "Weak Curative"
Actual: the inventory rejects the Crystalline Pollen Cluster item.

- Try to put Short Mead into the input item slot with a bottle as the background.

Expected: the inventory accepts the Short Mead item.
Actual: the inventory rejects the Short Mead item.

I've got a local fix for strictly this bug, but after testing it out, there are other related issues.  It happens that doing nothing and letting this bug be a thing would be safer than fixing just this bug without any other changes at the same time.  I'll submit a pull request once I've tackled all the issues I can find.

### PR DESCRIPTION
**Pull request by airbreather**
This fixes #602.

In that issue, I mentioned some concern about some other things that started breaking.  Most of it was expected behavior (didn't initially notice the item entities getting dropped when closing the inventory the first few times), and the rest was an inconsistency between the alyzers and both the imprinter and infuser.

CLAHub is giving me a generic "We're sorry, but something went wrong." page after I agree to the CLA.  In case that's a problem, here's a message I signed with the [same key](http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xAD51C2580E479CD4) I've been using to sign all my dinky little Minecraft mods since September 2013:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Silly as it may seem to me to do such a formal thing for such a small
change, I don't like friction, so here goes.  I release this to the
public domain, using this template I got from unlicense.org:

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.20 (MingW32)

iQEcBAEBAgAGBQJVJddIAAoJEK1RwlgOR5zUxxcH/R6n5tgcEujdW0DiCBJ3I3Ed
rR7OmpN518h5U41JHiVZdABBoeYe0OgaJ2vAXCdSRvoJpKPSTeXr7Tsd6xpJcAA6
GwhyZ+LIHF3cbuNSwEvI9eHPWHErEiUMeIEynAzKVAWr1di66ECYU6tGk7HKXa7m
/fEdzLeasK0x2Vjw+62KjDXoilazJhcyrrRRO6mYxbXEsDYfBMwHdul0kUW8HQWD
eGt8p1h8VbbY7aH1OO/vqovLMi/+jl/fRaY2wV0rCtx+2UBVlx1N3DSQbtVbaWXm
fbjYbQY3oE836//dKmNsPHzuPbJ//8FvBN6/xXjDJQHR8DpLhQT/hmkEfx5Om0A=
=pdF+
-----END PGP SIGNATURE-----
```

### CODE REVIEW

**Comment by mezz** [comment]
Looks good. CLAHub is very buggy. 
Can you please update the PR by adding your name to this file? https://github.com/ForestryMC/ForestryMC/blob/dev/cla-signatures.txt
We're using it for anyone who can't sign on CLAHub. Thanks!

**Comment by airbreather** [comment]
257b779 deletes the code I commented out and the equivalent commented-out code that I followed for consistency.
5786a34 updates cla-signatures.txt.

**Comment by mezz** [comment]
Perfect! I'll merge this in tonight.

**Comment by mezz** [comment]
Added here: https://github.com/ForestryMC/ForestryMC/commit/0462e5a9303bd4f45bb46ec7aa785f19e8f51b01
Thanks again!

**Pull request closed without merging**
