### PR TITLE
add invtweaks to build.gradle

### PR DESCRIPTION
**Pull request by temp1011**
Inventory tweaks was causing problems for me. Since curse has a maven API I thought it would be worthwhile to add it to the developer project to make setting up a workspace easier.

### CODE REVIEW

**Comment by temp1011** [comment]
It's easier to access the other maven and see what's there, curseforge requires an API token to check theirs through a web browser.

**Comment by mezz** [comment]
I don't really like using invtweaks, I would prefer it was not part of the developer workspace by default.
It uses a coremod, which is probably why it is difficult to get working. Ideally we should not test Forestry in an environment with coremods, since they can change the game behavior in unexpected ways.

**Comment by temp1011** [comment]
I'll see if I can fix the issues I was having. The API doesnt contain any coremod parts though from what I can see.

**Comment by temp1011** [comment]
~So IDEA seems to forget where everything is when switching branches for me. Not sure why but it's easy to fix every time but slightly annoying.~ It just can't find the API folder. Maybe something to do with linux? It's not a huge problem to fix either way.

**Pull request closed without merging**
