### PR TITLE
1.8.8 Version

### PR DESCRIPTION
**Pull request by Nedelosk**
I have started to develop the version 1.8.8 of ForestryMC.

### CODE REVIEW

**Comment by Nedelosk** [comment]
The Version is finished.

**Comment by Nedelosk** [comment]
- [ ] add All Models
- [ ] Fix Bugs

**Comment by Nedelosk** [comment]
@mezz  The 1.8.8 ForestryMC Version is now complete.

**Comment by mezz** [comment]
Great! Thank you @Nedelosk. I will start work from here.

**Comment by Nedelosk** [comment]
I will help you, when I can.

**Comment by mezz** [comment]
Is this up-to-date with dev branch? I am not able to merge because there are so many conflicts.

**Comment by Nedelosk** [comment]
What do you mean with up-to-date ? It's all commits from the dev branch in this PR or it's all code from the dev branch in this PR ?

**Comment by mezz** [comment]
I mean all commits from dev

**Comment by Nedelosk** [comment]
Than it's not up-to-date. I make a new PR with all commits.

**Pull request closed without merging**
