### PR TITLE
Updated ru_ru.lang

### PR DESCRIPTION
**Pull request by Radviger**
- Updated ru_ru.lang
- Fixed research note chat message translation
- Fixed duplicated (client+server) multiblock error message

### CODE REVIEW

**Comment by Romz24** [comment]
good translation

**Comment by Radviger** [comment]
Yet still not finished : )

**Comment by Nedelosk** [comment]
@Radviger What is the current state ?

**Comment by Radviger** [comment]
@Nedelosk Guide book is not completely translated yet (Only one or two first sections are fully-translated). You can merge what's already done if that's ok.

**Pull request merged**
