### PR TITLE
Update PluginMagicalCrops.java

### PR DESCRIPTION
**Pull request by miuirussia**
Fixed for latest MagicalCrops

### CODE REVIEW

**Comment by Nirek-K** [comment]
Er, the current plugin works as expected for the latest public beta on CurseForge.  (If there's some other version floating around, I wll update compatibilty when it turns up as a beta on curse)

**Comment by miuirussia** [comment]
With this version (BETA 5):
http://minecraft.curseforge.com/projects/magical-crops-core/files/2245371

integration not working!

**Comment by Nirek-K** [comment]
Ah I see, for some bizzare reason they decided to make a completely new project for beta4-5, the one I've always ever found has been on beta3 for a while. I'll see what all they changed and have some for today. Sorry about that.

**Comment by miuirussia** [comment]
I can send items dump, they changed all names (now they don't use magicalcrops_ prefix)

**Comment by miuirussia** [comment]
prefix*

**Comment by Nirek-K** [comment]
Just pushed a commit that should fix everything with Beta5, including the new crops added since 3. Give that a go.

**Comment by miuirussia** [comment]
Thanks!

**Pull request closed without merging**
