### PR TITLE
[WIP] Chests now render akin to the vanilla chests

### PR DESCRIPTION
**Pull request by buttilda**
This is not done yet!

-What should I do with the old textures? I haven't found a way to prevent them from being registered and causing those awful checkered textures from showing up (as breaking particles).

-Can anyone help me with the new textures? I'm horrible at texturing =P I made them look like the current ones but I can't find a way to fit the top face in without making it look weird.

-Bounding boxes can't be set on a per-block basis on BlockBase. Since lepidopterology and arboriculture chests are the only ones registered that problem could be worked around, but for apiculture changing the bounding box would affect other blocks (like the apiaries). How should I proceed?

-This is fully compatible with the current version of Forestry! I thought I'd have to break compatibility but turns out I didn't :D

-Other than that it all works! The lid animates perfectly and the sound plays as well.

### CODE REVIEW

**Comment by buttilda** [comment]
Added a commit with a suggestion on how to solve the bounding box problem.

I'll squishy everything after this is all decided :3 Leaving it like this makes it easier to follow.

**Comment by mezz** [comment]
Just noting: This PR is for issue #806 

You did the textures right: delete the old ones and make sure the new ones have a different name for texture pack compatibility.

The old icons are registered in `MachineDefinition.registerIcons`. Unfortunately, the best way may be to subclass MachineDefintion and override that method. That should fix the breaking particles as well.

I can help with the top texture, but I can't do it right now and I'm about to be gone for short vacation.

Doing bounding box with the machine definition looks like the right way.

Code looks good! Thanks ganymedes.

**Comment by buttilda** [comment]
I'm glad everything is of accordance :)
I'll get started on fixing the rest.

**Comment by buttilda** [comment]
Gave the textures a go
screen shot 2015-08-27 at 19 03 52

All I did was scale the pattern down... so anyone who can do better please do feel free!

**Comment by buttilda** [comment]
Also managed to fix the broken textures by simply not setting the face numbers in the MachineDefinition. Deleted all of the old textures but one, which will be used for the particles (I found that using the full chest texture creates weird looking particles, but that might just be me being picky). Let me know if you like that solution. Committing it all now.

**Comment by MysteriousAges** [comment]
Damn, this looks good!

**Comment by buttilda** [comment]
Thanks :3
Do you wanna merge it? I can squash the commits if you think this is good enough.

**Comment by mezz** [comment]
Just got back from vacation. I would like to take a stab at improving the textures before merging this. It looks great!

**Comment by mezz** [comment]
Updated the textures so the glass area takes up the whole top instead of resizing it.

**Comment by mezz** [comment]
Committed here: https://github.com/ForestryMC/ForestryMC/commit/5cd2350c9bcf4b634b25938c56d31356d7afb212

**Pull request closed without merging**
