### PR TITLE
Update to latest BuildCraft

### PR DESCRIPTION
**Pull request by ganymedes01**
Not sure if you'd want to do this now, but whenever you decide to, it's done :3

### CODE REVIEW

**Comment by LouisHutch** [comment]
https://github.com/ForestryMC/ForestryMC/issues/396

**Comment by mezz** [comment]
Not ready for this yet. If possible I'd like to move the pipe to BC Compat since it's much more tied to BC's updates than it is to Forestry's. Covert and Sengir are on board with the idea.

**Comment by asiekierka** [comment]
@mezz: I think the move should be done in Forestry 3.6, personally, and the pipe kept in Forestry 3.5. That way users will get a grace period to move. Anyway, 3.5 still needs an update.

**Comment by mezz** [comment]
I would like to cap the compatible BC Transport API version on Forestry so it does not crash on BC 7, and then add the pipe to BC Compat. It can handle the pipe for BC 7+.

**Comment by asiekierka** [comment]
That's fine, but you should also add a missing mapping patch to one of these so worlds do not break.

**Comment by mezz** [comment]
Yep, that's the first thing I got working :+1:

**Comment by mezz** [comment]
PR to move Apiarist's pipe to BC Compat is complete: https://github.com/BuildCraft/BuildcraftCompat/pull/20
When it's pulled I will close this issue.

**Comment by asiekierka** [comment]
Keep in mind to make the Apiarist Pipe module for Forestry 3.5.x stay for BC < 7.0.x. In 3.6, it should be removed.

**Comment by mezz** [comment]
The Apiarist Pipe in Forestry is left active for BC 6 and disabled for BC 7 right now. If both mods have the pipe, there is no conflict. When their BC is upgraded to 7, all Apiarist Pipes become BC Compat.

**Comment by Vexatos** [comment]
@asiekierka It should automatically remap if possible.

**Comment by mezz** [comment]
It automatically remaps. If you get a forge warning that it's missing, be sure to update BC Compat before continuing.

**Pull request closed without merging**
